[tool.poetry]
name = "chess-bot"
version = "0.1.0"
description = ""
authors = ["Aaro Koivukangas <aaro.koivukangas@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
